apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "{{ .Release.Name }}-kv"
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.container.port }}
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:

        - name: ASPNETCORE_URLS
          value: "{{ .Values.aspnetcore.urls }}"

        - name: AzureAd__Instance
          value: "{{ .Values.azureAd.instance }}"

        - name: Authorization__CartApiAccessRole
          value: "{{ .Values.authorization.cartApiAccessRole }}"

        - name: AzureAd__TenantId
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: AzureAd__TenantId

        - name: AzureAd__ClientId
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: AzureAd__ClientId

        - name: AzureAd__Audience
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: AzureAd__Audience

        - name: ConnectionStrings__CartDb
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: ConnectionStrings__CartDb

            - name: UserApi__BaseUrl
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: UserApi__BaseUrl

            - name: UserApi__Resource
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: UserApi__Resource

            - name: UserApi__TenantId
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: UserApi__TenantId

            - name: UserApi__ClientId
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: UserApi__ClientId

            - name: UserApi__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: UserApi__ClientSecret

        resources:
{{ toYaml .Values.resources | indent 10 }}