apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-kv
spec:
  provider: azure
  secretObjects:
  - secretName: {{ .Release.Name }}-secrets
    type: Opaque
    data:
    - objectName: cartapi-AzureAd--TenantId
      key: AzureAd__TenantId
    - objectName: cartapi-AzureAd--ClientId
      key: AzureAd__ClientId
    - objectName: cartapi-AzureAd--Audience
      key: AzureAd__Audience
    - objectName: ConnectionStrings--CartDb
      key: ConnectionStrings__CartDb
    - objectName: cartapi-UserApi--BaseUrl
      key: UserApi__BaseUrl
    - objectName: cartapi-UserApi--Resource
      key: UserApi__Resource
    - objectName: cartapi-UserApi--TenantId
      key: UserApi__TenantId
    - objectName: cartapi-UserApi--ClientId
      key: UserApi__ClientId
    - objectName: cartapi-UserApi--ClientSecret
      key: UserApi__ClientSecret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.keyVault.managedIdentityClientId }}"
    keyvaultName: "{{ .Values.keyVault.name }}"
    tenantId: "{{ .Values.keyVault.tenantId }}"
    objects: |
      array:
        - |
          objectName: cartapi-AzureAd--TenantId
          objectType: secret
        - |
          objectName: cartapi-AzureAd--ClientId
          objectType: secret
        - |
          objectName: cartapi-AzureAd--Audience
          objectType: secret
        - |
          objectName: ConnectionStrings--CartDb
          objectType: secret
        - |
          objectName: cartapi-UserApi--BaseUrl
          objectType: secret
        - |
          objectName: cartapi-UserApi--Resource
          objectType: secret
        - |
          objectName: cartapi-UserApi--TenantId
          objectType: secret
        - |
          objectName: cartapi-UserApi--ClientId
          objectType: secret
        - |
          objectName: cartapi-UserApi--ClientSecret
          objectType: secret