apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-kv
spec:
  provider: azure
  secretObjects:
  - secretName: {{ .Release.Name }}-secrets
    type: Opaque
    data:
    - objectName: userapi-AzureAd--TenantId
      key: AzureAd__TenantId
    - objectName: userapi-AzureAd--ClientId
      key: AzureAd__ClientId
    - objectName: userapi-AzureAd--Audience
      key: AzureAd__Audience
    - objectName: ConnectionStrings--UserDb
      key: ConnectionStrings__UserDb
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.keyVault.managedIdentityClientId }}"
    keyvaultName: "{{ .Values.keyVault.name }}"
    tenantId: "{{ .Values.keyVault.tenantId }}"
    objects: |
      array:
        - |
          objectName: userapi-AzureAd--TenantId
          objectType: secret
        - |
          objectName: userapi-AzureAd--ClientId
          objectType: secret
        - |
          objectName: userapi-AzureAd--Audience
          objectType: secret
        - |
          objectName: ConnectionStrings--UserDb
          objectType: secret